### ISSUE TITLE
[Feature Request] Windowed Mode

### ISSUE THREAD

**Issue by HeteroChromia42** [gaycoderprincess/TiRTweaks#1]
If i recall correctly, TiR doesn't have a standard "Windowed" Mode. While Borderless Windowed Mode allows you to run the game on a borderless window, i'd love to have a bordererd window option too, as it makes it easier to drag it around.

**Comment by gaycoderprincess** [comment]
Added in v1.36! ^^
There was already a built-in windowed mode option in syscfg.ini (the line that's usually F) but it wasn't actually exposed in the config app it seems
I made the window non-resizable for now since changing resolution & aspect ratio mid-session leads to all sorts of issues currently, maybe I'll look into that further sometime
